name: byte_token_example
description: A sample command-line application.
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ^3.0.0

dependencies:
  byte_token: ^2.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
