name: byte_token
description: A protobuf based, performant and lightweight token authentication package.
version: 2.0.0
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: ^3.2.0

dependencies:
  crypto: ^3.0.3
  fixnum: ^1.1.0
  protobuf: ^2.1.0
  yak_utils: ^2.0.0
  
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
