name: yak_test
description: a Dart package that helps to testing apps made with `yak_packages`
version: 2.0.1
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: ^3.2.0
  flutter: '>=3.16.0'

dependencies:
  meta: ^1.10.0
  yak_runner: ^2.0.0
  stub: ^2.0.0
  test: ^1.24.9

dev_dependencies:
  mocktail: ^0.3.0
  lints: ^3.0.0


